USE PROYECTO;
CREATE TABLE FACTURA(
    FACTURAS_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    CONSULT_ID INT,
    FECHA_FACTURA DATE,
    MONTO DECIMAL(10.2),
    METODO_PAGO VARCHAR(50),
    FOREIGN KEY (CONSULT_ID) REFERENCES CONSULT(CONSULT_ID)
);
DROP TABLE factura;
-- TABLA PARA LOS DOCTORES DOCTORES 
CREATE TABLE DOCTOR(
    DOCTOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    ESPECIALIDAD VARCHAR(50)
);



-- CREATE TABLE PARA LAS CONSULTAS 
CREATE TABLE CONSULT(
    CONSULT_ID INT AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT, 
    DOCTOR_ID INT, 
    TRATAMIENTO VARCHAR(50),
    FECHA_CONSULT DATE,
    FOREIGN KEY (usuario_id) REFERENCES USUARIOS (usuario_id),
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID) 
);






CREATE TABLE HISTORIAL_FACT_USER(
    HFACT_USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT,
    factura_id INT,
    FOREIGN KEY (usuario_id) REFERENCES USUARIOS (usuario_id),
    FOREIGN KEY (factura_id) REFERENCES FACTURA (factura_id)
);


